baseURL: "https://pier8software.co.uk/"
languageCode: "en-gb"
title: "Pier 8 Software"
Paginate: 15
params:
    description: "A simple clean HUGO blog template"
    author: Red Sparrow Themes
    keywords: Blog, Personal Blog, Travel, Food